### ISSUE TITLE
With WP Flywheel

### ISSUE THREAD

**Issue by andresantiagohellmann** [infinum/eightshift-boilerplate-plugin#16]
### Describe the question we can answer

Is it possible to use boilerplate with localwp flywheel? I have the error "Error establishing a database connection" when using wp plugin enable themename

### Environment info

- PHP 8.1.10
- Environment WPLocal
- MAC OS Monterey

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by mbmjertan** [comment]
Hi, André! 

It should be possible to use Boilerplate with Flywheel. We haven't heard any reports that would suggest otherwise, and we've had people use Flywheel and Boilerplate.

Do you encounter that issue with the default WordPress setup? Can you access the database using a MySQL client? Is the database server up and running? You can try that by using `mysql -u [username] -p [password]` in the terminal, and using `use [database];` afterwards.

Enabling the boilerplate (for either plugins or themes) doesn't do anything to your database or wp-config, apart from WP Core storing plugin/theme metadata, so it would really be a surprise for me that this is happening only when a boilerplate-bootstrapped plugin or theme is enabled.

**Comment by andresantiagohellmann** [comment]
Hello Mario!
I'd like to thank you for the quick response, I'm really not ready to be able to use Eightshift development. Answering your questions... Yes I encounter these issues with the default wordpress configuration, and yes, I have access to the database.
I did a fresh install via steering wheel to make sure the problem wasn't with the current install. Follow the steps:
01 - I created a new website with the steering wheel
02 - I navigated to the plugins directory through the terminal and gave the command "npx create-wp-project plugin"
03 - After answering the questions and the installation, I executed the first command of the suggested steps "wp plugin activate eightshift-plugin"
04 - I received the error: Error: Error establishing a database connection.

I made a print of the screens, if you want to look... https://trydo.com.br/Eightshift.pdf

**Comment by andresantiagohellmann** [comment]
> Hi, André!
> 
> It should be possible to use Boilerplate with Flywheel. We haven't heard any reports that would suggest otherwise, and we've had people use Flywheel and Boilerplate.
> 
> Do you encounter that issue with the default WordPress setup? Can you access the database using a MySQL client? Is the database server up and running? You can try that by using `mysql -u [username] -p [password]` in the terminal, and using `use [database];` afterwards.
> 
> Enabling the boilerplate (for either plugins or themes) doesn't do anything to your database or wp-config, apart from WP Core storing plugin/theme metadata, so it would really be a surprise for me that this is happening only when a boilerplate-bootstrapped plugin or theme is enabled.

Hello again Mario.
I found that the OS was restricting the app's activation permissions. Given the proper permissions everything went well. Sorry for the inconvenience and thanks for the support.
